

const theGirlAndThePlaneTree: Record<string, string[]> = { 
   alb: [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/albanian-cover-corrected1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/albanian/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/albanian/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/albanian/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/albanian/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/albanian/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/albanian/7-correction.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/albanian/8-correction.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/albanian/9-correction.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/albanian/10-correction.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/albanian/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/albanian/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/albanian/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/albanian/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/albanian/15-correction.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/albanian/16-correction.webp",
  ],

    chin: [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/chinese/16.webp",
  ],

    croat: [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/croatian-cover-corrected.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/croatian/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/croatian/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/croatian/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/croatian/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/croatian/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/croatian/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/croat/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/croat/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/croat/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/croat/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/croat/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/croatian/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/croatian/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/croat/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/croat/16.webp", 
  ],

  en: [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/thegirl-allimages/16.webp",
  ],

    fr: [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/french/16.webp",
  ],

    ger: [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/german/16.webp",
  ],

    gr:[
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/greek/16.webp",
  ],
  
    it: [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/italian/16.webp",
  ],

    port:[
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/portuguese-cover-corrected.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/portuguese/16.webp",
  ],


 
  cat: [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/catalan/16.webp",
  ],


  rom:[
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/romanian/16.webp",
   
  ],
  rus:[
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/russian/16.webp",

  ],
  ser: [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/serbian/16.webp",
  
  ],
  
  span : [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/spanish/16.webp",
  ],

  

  standarab:[
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/arabic/16.webp",
  ],


  swa: [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swahili-cover-corrected.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/languages/swahili/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swahili/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swahili/16.webp",
  ],

  swed: [
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/swedish/16.webp",
  ],


  viet:[
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/1.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/2.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/3.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/4.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/5.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/6.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/7.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/8.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/9.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/10.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/11.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/12.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/13.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/14.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/15.webp",
    "https://static.igem.wiki/teams/5684/wikipics/human-practices/fairytails/the-girl-corrections/vietnamese/16.webp",
    
  ],

  




};

export default theGirlAndThePlaneTree;